### PR TITLE
Finished 6th Project of Microverse - Awaiting for Review

### PR DESCRIPTION
**Pull request by Dandush03**
For this project, we:
- Used float to position the first two sections
- Used flexbox to position the rest of the sections
- Used different widths to resize all the sections with media queries (to make the page responsive)

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi Team, you have done a great job so far. :raised_hands:  Congratulations on the job. :+1: 
Here are a few changes to get the project approved :slightly_smiling_face: 
Find comment below:
- Kindly check this [link](https://jigsaw.w3.org/css-validato) to see the errors
fet
- The image stretches on a small screen.
str

Kindly fix these changes and submit code review :+1: 
Happy coding :computer: 
[DANIEL](https://www.linkedin.com/in/daniel-larbi-addo-9738b0128/)

**Comment by Dandush03** [comment]
Hello,

Updated CSS File after Validator Checks && Fixed Hight Issues

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
